# Site settings
title: LikeJekyll
email: info@likejekyll.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://likejekyll.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
