# Site settings
title: LikeJekyll
email: info@likejekyll.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://likejekyll.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Assets
assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  js_compressor: uglifier
  css_compressor: yui

# Other
mode: production
